### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by tisto** [johansatge/psi-report#5]
System:

- Ubuntu 16.04 (can reproduce the problem on OS X)
- Node 8.9.3
- psi-report installed locally with "yarn add psi-report --dev" or "npm install psi-report --save-dev" (same problem when installed globally)

When running psi-report I get the following traceback:

```
$ node_modules/psi-report/src/cli.js https://kitconcept.com report.html
Found https://kitconcept.com/
Found https://kitconcept.com/blog/
Found https://kitconcept.com/blog/pastanaga-sprint-bonn-2017-report/
Found https://kitconcept.com/blog/headless-and-mobile-the-future-of-plone/
Found https://kitconcept.com/blog/plone-beethoven-sprint-2017-sprint-report-day-3/
Found https://kitconcept.com/blog/plone-beethoven-sprint-report-day-2/
Found https://kitconcept.com/blog/plone-beethoven-sprint-2017-sprint-report-day-1/
Found https://kitconcept.com/blog/continuous-integration-for-plone/
2017-12-21T08:34:31.157Z - warn: CRAWLER response body is not HTML, skip injecting. Set jQuery to false to suppress this message
2017-12-21T08:34:31.159Z - warn: CRAWLER response body is not HTML, skip injecting. Set jQuery to false to suppress this message
2017-12-21T08:34:31.160Z - warn: CRAWLER response body is not HTML, skip injecting. Set jQuery to false to suppress this message
2017-12-21T08:34:31.164Z - warn: CRAWLER response body is not HTML, skip injecting. Set jQuery to false to suppress this message
2017-12-21T08:34:31.167Z - warn: CRAWLER response body is not HTML, skip injecting. Set jQuery to false to suppress this message
2017-12-21T08:34:31.186Z - warn: CRAWLER response body is not HTML, skip injecting. Set jQuery to false to suppress this message
Found https://kitconcept.com/plone-beethoven-sprint-bonn-2017/
2017-12-21T08:34:31.230Z - warn: CRAWLER response body is not HTML, skip injecting. Set jQuery to false to suppress this message
2017-12-21T08:34:31.238Z - warn: CRAWLER response body is not HTML, skip injecting. Set jQuery to false to suppress this message
2017-12-21T08:34:31.265Z - warn: CRAWLER response body is not HTML, skip injecting. Set jQuery to false to suppress this message
2017-12-21T08:34:31.276Z - warn: CRAWLER response body is not HTML, skip injecting. Set jQuery to false to suppress this message
2017-12-21T08:34:31.311Z - warn: CRAWLER response body is not HTML, skip injecting. Set jQuery to false to suppress this message
2017-12-21T08:34:31.350Z - warn: CRAWLER response body is not HTML, skip injecting. Set jQuery to false to suppress this message
2017-12-21T08:34:31.369Z - warn: CRAWLER response body is not HTML, skip injecting. Set jQuery to false to suppress this message
2017-12-21T08:34:31.373Z - warn: CRAWLER response body is not HTML, skip injecting. Set jQuery to false to suppress this message
2017-12-21T08:34:31.384Z - warn: CRAWLER response body is not HTML, skip injecting. Set jQuery to false to suppress this message
2017-12-21T08:34:31.393Z - warn: CRAWLER response body is not HTML, skip injecting. Set jQuery to false to suppress this message
2017-12-21T08:34:31.401Z - warn: CRAWLER response body is not HTML, skip injecting. Set jQuery to false to suppress this message
2017-12-21T08:34:31.402Z - warn: CRAWLER response body is not HTML, skip injecting. Set jQuery to false to suppress this message
Got PSI data (mobile) for https://kitconcept.com/blog/
Got PSI data (desktop) for https://kitconcept.com/blog/
Got PSI data (desktop) for https://kitconcept.com/
Got PSI data (mobile) for https://kitconcept.com/
Got PSI data (mobile) for https://kitconcept.com/blog/pastanaga-sprint-bonn-2017-report/
Got PSI data (desktop) for https://kitconcept.com/blog/pastanaga-sprint-bonn-2017-report/
Got PSI data (mobile) for https://kitconcept.com/blog/headless-and-mobile-the-future-of-plone/
Got PSI data (mobile) for https://kitconcept.com/blog/plone-beethoven-sprint-2017-sprint-report-day-3/
Got PSI data (desktop) for https://kitconcept.com/blog/plone-beethoven-sprint-2017-sprint-report-day-3/
Got PSI data (mobile) for https://kitconcept.com/blog/plone-beethoven-sprint-report-day-2/
Got PSI data (desktop) for https://kitconcept.com/blog/headless-and-mobile-the-future-of-plone/
Got PSI data (mobile) for https://kitconcept.com/blog/plone-beethoven-sprint-2017-sprint-report-day-1/
Got PSI data (desktop) for https://kitconcept.com/blog/plone-beethoven-sprint-2017-sprint-report-day-1/
Got PSI data (desktop) for https://kitconcept.com/blog/plone-beethoven-sprint-report-day-2/
Got PSI data (mobile) for https://kitconcept.com/blog/continuous-integration-for-plone/
Got PSI data (desktop) for https://kitconcept.com/blog/continuous-integration-for-plone/
Got PSI data (mobile) for https://kitconcept.com/plone-beethoven-sprint-bonn-2017/
Got PSI data (desktop) for https://kitconcept.com/plone-beethoven-sprint-bonn-2017/
/home/timo/workspace/elif/frontend/node_modules/psi-report/src/html_report.js:47
                html = html.replace('<!--results-->', _buildItem(templates.item, page) + '<!--results-->');
                            ^

TypeError: Cannot read property 'replace' of undefined
    at /home/timo/workspace/elif/frontend/node_modules/psi-report/src/html_report.js:47:29
    at Array.map (<anonymous>)
    at _onTemplatesLoaded (/home/timo/workspace/elif/frontend/node_modules/psi-report/src/html_report.js:45:18)
    at /home/timo/workspace/elif/frontend/node_modules/psi-report/node_modules/async/dist/async.js:3874:9
    at /home/timo/workspace/elif/frontend/node_modules/psi-report/node_modules/async/dist/async.js:473:16
    at iterateeCallback (/home/timo/workspace/elif/frontend/node_modules/psi-report/node_modules/async/dist/async.js:980:24)
    at /home/timo/workspace/elif/frontend/node_modules/psi-report/node_modules/async/dist/async.js:958:16
    at /home/timo/workspace/elif/frontend/node_modules/psi-report/node_modules/async/dist/async.js:3871:13
    at ReadFileContext.callback (/home/timo/workspace/elif/frontend/node_modules/psi-report/src/html_report.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
```

@johansatge thank you for sharing your work! If you have a pointer how to fix this or work around the issue that would be highly appreciated!

**Comment by dasrick** [comment]
Same problem here. (using v2.2.0)

**some details**

`html.replace` is undefined because of missing template. (should be loaded in `src/html_report.js:22`)
The template files are missing in npm package since v2.1.0

**Reason**

Since v2.1.0 there are two more lines in `.gitignore` (*.txt, *.html). So npm will ignore all that files for publishing.

**possible fixes**

1. remove ´*.html´ from ´.gitnore´
2. OR: add a separate ´.npmignore´ that looks like ´.gitnore´ but without excluding html files

@johansatge which fix you would prefer?

**Comment by jpatovh** [comment]
My bad, sorry guys. Here's the patch: https://github.com/johansatge/psi-report/pull/6 .

**Comment by johansatge** [comment]
Thanks everyone for spotting and fixing this issue! It should be good with version `2.2.1`, published a few minutes ago.

**Comment by tisto** [comment]
Works like a charm now. Thank you for the quick reaction and fix @johansatge!
